import store from '../store/index.js'
let language = store.getState().getIn(['pageUI','language']);
console.log('language:',language);
let regZH = /zh/i,
    regEN = /en/i;
if(regZH.test(language)){
    module.exports = {
        ERROR1000: '服务器开了个小差',
        ERROR1001: 'token解析失败',
        ERROR1002: '用户已存在',
        ERROR1003: '用户不存在',
        ERROR1004: '密码错误',
        ERROR1005: '房间不存在',
        ERROR1006: '文件类型错误',
        ERROR1007: '文件过大',
        ERROR1008: '文件读取失败',
        ERROR1009: '文件上传失败',
        ERROR10010: '超出限制，用户最多能创建3个房间',
        ERROR10011: '成功创建房间',
        ERROR10012: '该房间已存在',
        ERROR10013: '权限不足',
        
        
        email: '邮箱',
        nickname: '昵称',
        password: '密码',
        Login: '登录',
        SignUp: '注册',
        inputAreaPlaceholder: '输入消息...',
        emoji: '表情包',
        send: '发送',
        group: '群组',
        private: '私聊',
        AM: '上午',
        PM: '下午',
        conversation: '新建对话',
        startConv: 'Start a conversation',
        userProfile: '用户资料',
        nickname: '昵称',
        status: '状态',
        userProfileTran: 'This is not your pin. This name will be visible to your app contacts.',
        groupInfo: 'Group info',
        bulletin: 'Bulletin',
        participants: 'Participants',
        addPart: 'Add participant',
        inviteLink: 'Invite to Group via Link',
        contactInfo: 'Contact info',
        newGroup: 'New Group',
        success: 'success',
        inviteTitle: 'Invite via link',
        inviteLinkDisabled: '链接失效',
        joinRoomSuccess: '成功加入房间',
        logout: '登出',
        sendInviteLink: '发送邀请链接',
        sendInviteLinkByNami: '使用 nami 发送链接',
        copyLink: '复制链接',
        refreshLink: '更新链接',
        copiedLink: '链接已复制到剪贴板',
        linkTran: 'Anyone with NAMI can follow this link to join this group. Only share it with people you trust.',
        newContact: '新建对话',
        participants: '群组成员',
        search: '搜索...',
        menu: '菜单',
        attach: '附件',
        addExpression: '成功添加表情',
    }
}else{
    module.exports = {
        ERROR1000: 'Server error',
        ERROR1001: 'Token parsing failed',
        ERROR1002: 'User already exists',
        ERROR1003: 'User doesn‘t exist',
        ERROR1004: 'Password error',
        ERROR1005: 'Room doesn‘t exist',
        ERROR1006: 'File type error',
        ERROR1007: 'The file is too large',
        ERROR1008: 'File read error',
        ERROR1009: 'File upload error',
        ERROR10010: '超出限制，用户最多能创建3个房间',
        ERROR10011: '成功创建房间',
        ERROR10012: '该房间已存在',
        ERROR10013: 'Insufficient permissions',

        email: 'email',
        nickname: 'nickname',
        password: 'password',
        Login: 'Login',
        SignUp: 'SignUp',
        inputAreaPlaceholder: 'type a message',
        emoji: 'emoji',
        send: 'send',
        group: 'Group',
        private: 'Private',
        AM: 'am',
        PM: 'pm',
        conversation: 'New Conversation',
        startConv: 'Start a conversation',
        userProfile: 'Profile and status',
        nickname: 'nickname',
        status: 'status',
        userProfileTran: 'This is not your pin. This name will be visible to your app contacts.',
        groupInfo: 'Group info',
        bulletin: 'Bulletin',
        participants: 'Participants',
        addPart: 'Add participant',
        inviteLink: 'Invite to Group via Link',
        contactInfo: 'Contact info',
        newGroup: 'New Group',
        success: 'success',
        inviteTitle: 'Invite via link',
        inviteLinkDisabled: 'Invite link disabled',
        joinRoomSuccess: 'joined room',
        logout: 'Logout',
        sendInviteLink: 'send invite link',
        sendInviteLinkByNami: 'Send link via nami',
        copyLink: 'Copy link',
        refreshLink: 'Refresh link',
        copiedLink: 'Link copied to clipboard',
        copyError: 'error',
        linkTran: 'Anyone with nami can follow this link to join this group. Only share it with people you trust.',
        newContact: 'New Contact',
        participants: 'Participants',
        search: 'search...',
        menu: 'menu',
        attach: 'attach',
        addExpression: 'added expression',
        
    }
}