module.exports = {
    ROBOT_NAME: '机器人小z',
    INIT_ROOM: 'MDZZ',
    INIT_ROOM_INFO: '有问题欢迎提issue',
    INIT_ADMIN_EMAIL: 'mdzz',
    DEFAULT_AVATAR: 'http://oj7h98lzb.bkt.clouddn.com/user.svg',
    DEFAULT_GROUP_AVATAR: 'http://oj7h98lzb.bkt.clouddn.com/download.svg',
    DAY: 24*60*60*1000,
    JWT_KEY: 'JWT_KEY',
    ROBOT_URL: 'http://www.tuling123.com/openapi/api',
    ROBOT_KEY: '273e3ca4189a3fc03b4a94db8d87796b',
    ROBOT_AVATAR:'http://oajmk96un.bkt.clouddn.com/robot.jpg',
    QINIU_ACCESS_KEY: 'WfabXLWGFotFsoyqTz-fL7gmD_wVjtNGa3sTmE3O',
    QINIU_SECRET_KEY: '8i3OPlKmgURNH3WQQjqbga-tYwN0r92XnnBdx8Ie',
    QINIU_CNAME: 'http://oj7h98lzb.bkt.clouddn.com',
    QINIU_BUCKET: 'mdzz',
    MAX_ROOM: 5,
    MAX_BLOCK: 30,
}