// roomList
export const INIT_ROOM_LIST = 'ROOM_INIT_LIST';
export const ADD_ROOM_ITEM = 'ROOM_ADD_ITEM';
export const REMOVE_ROOM_ITEM = 'REMOVE_ROOM_ITEM';
export const PUSH_HISTORY = 'ROOM_PUSH_HISTORY';
export const UNSHIFT_HISTORY = 'ROOM_UNSHIFT_HISTORY';
export const MERGE_ROOM_INFO = 'MERGE_ROOM_INFO';
export const ADD_UNREAD_COUNT = 'ADD_UNREAD_COUNT';
export const CLEAR_UNREAD_COUNT = 'CLEAR_UNREAD_COUNT';