export const SET_LEFT_MANAGER = 'SET_LEFT_MANAGER'; // 右侧菜单状态
export const SET_RIGHT_MANAGER = 'SET_RIGHT_MANAGER'; // 右侧菜单状态

export const SET_LOADING_STATE = 'SET_LOADING_STATE';

export const PUSH_SNACKBAR = 'PUSH_SNACKBAR';
export const SHIFT_SNACKBAR = 'SHIFT_SNACKBAR';

export const MESSAGE_CONTAINER_SCROLL = 'MESSAGE_CONTAINER_SCROLL';

export const SET_EXPRESSION_STATE = 'SET_EXPRESSION_STATE';

export const SET_NOTIFICATIONS_STATE = 'SET_NOTIFICATIONS_STATE';

export const SET_MENU_STATE = 'SET_MENU_STATE';
export const SET_OWL_STATE = 'SET_OWL_STATE';